import type { Metadata, Viewport } from 'next';
import '../../styles/globals.css';


export const metadata: Metadata = {
  title: '아무거나',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='kr'>
      <body >
        {children}
      </body>
    </html>
  );
}
