import type { Metadata, Viewport } from 'next';
import '../../styles/globals.css';
import Script from 'next/script';
import Header from './Header/header';


export const metadata: Metadata = {
  title: '아무거나',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='kr'>
      <body >
        <Script
            strategy="beforeInteractive"
            src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_MAP_KEY}&autoload=false`}
          />
        <Header />
        {children}
      </body>
    </html>
  );
}
